# Generated by Django 4.2.2 on 2023-06-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del producto', max_length=100)),
                ('descripcion', models.CharField(help_text='Breve descripcion del producto', max_length=300, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('tipo', models.ManyToManyField(to='Aplicacion1.clasificacion')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
